version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    profiles: ["all", "schema"]
    command: --max_allowed_packet=209715200
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dolphinscheduler
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 60s
      retries: 120
    networks:
      - dolphinscheduler

  dolphinscheduler-zookeeper:
    image: bitnami/zookeeper:3.6.2
#    platform: linux/arm64
    container_name: dolphinscheduler-zookeeper
    ports:
      - "2181:2181"
    profiles: ["all"]
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_4LW_COMMANDS_WHITELIST: srvr,ruok,wchs,cons
    volumes:
      - ./data/dolphinscheduler-zookeeper:/bitnami/zookeeper
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/2181"]
      interval: 5s
      timeout: 60s
      retries: 120
    networks:
      - dolphinscheduler

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    profiles: ["all"]
    ports:
      - "9092:9092"        # PLAINTEXT 外部端口
      - "29092:29092"      # PLAINTEXT_EXTERNAL 外部端口
#    environment:
#      - KAFKA_ZOOKEEPER_CONNECT=dolphinscheduler-zookeeper:2181
#      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_EXTERNAL://0.0.0.0:29092
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_EXTERNAL://192.168.0.105:29092
#      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
#      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT

    environment:
      - KAFKA_ZOOKEEPER_CONNECT=dolphinscheduler-zookeeper:2181  # 指定 Zookeeper 地址
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092  # 监听所有网络接口上的 9092 端口
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092  # 只对 Kafka 客户端返回容器内部的地址
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT  # 仅支持 PLAINTEXT，无需 EXTERNAL
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT  # 让 Kafka 内部通信使用 PLAINTEXT 监听器
#      - KAFKA_LOG_RETENTION_HOURS=168  # 设置日志保留 7 天（可选优化）
#      - KAFKA_LOG_SEGMENT_BYTES=1073741824  # 每个日志分片 1GB（可选优化）
#      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true  # 允许自动创建主题（可选）

    volumes:
      - ./data/kafka:/bitnami/kafka
#      - ./data/etc/localtime:/etc/localtime
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"
    networks:
      - dolphinscheduler

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    profiles: ["all"]
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - dolphinscheduler

  doris:
    image: yagagagaga/doris-standalone:2.1.5
    platform: linux/arm64
    container_name: doris
    profiles: ["all"]
    hostname: doris
    ports:
      - "8030:8030"  # HTTP 服务
      - "8040:8040"  # BE 端口
      - "9030:9030"  # MySQL 访问端口
    volumes:
      - ./data/doris/doris_fe_meta:/opt/doris/fe/meta
      - ./data/doris/doris_be_storage:/opt/doris/be/storage
#    environment:
#      - DORIS_FE_IP=192.168.0.105
    networks:
      - dolphinscheduler
    command: >
      bash -c "sed -i 's/^priority_networks=.*/priority_networks=192.168.0.105\/24/' /opt/doris/fe/conf/fe.conf &&
               sed -i 's/^frontend_address=.*/frontend_address=192.168.0.105/' /opt/doris/fe/conf/fe.conf &&
               /opt/doris/bin/start_doris.sh --daemon &&
               tail -f /opt/doris/fe/log/fe.log"

  dolphinscheduler-schema-initializer:
    image: apache/dolphinscheduler-tools:3.1.9
    env_file: .env
    profiles: ["schema"]
    command: [ tools/bin/upgrade-schema.sh ]
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./data/dolphinscheduler-schema-initializer/dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - ./data/dolphinscheduler-schema-initializer/dolphinscheduler-shared-local:/opt/soft
      - ./data/dolphinscheduler-schema-initializer/dolphinscheduler-resource-local:/dolphinscheduler
      - ./jars/mysql-connector-java-8.0.16.jar:/opt/dolphinscheduler/tools/libs/mysql-connector-java-8.0.16.jar
    networks:
      - dolphinscheduler

  dolphinscheduler-api:
    image: apache/dolphinscheduler-api:3.1.9
    ports:
      - "12345:12345"
      - "25333:25333"
    profiles: ["all"]
    env_file: .env
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:12345/dolphinscheduler/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      dolphinscheduler-zookeeper:
        condition: service_healthy
    volumes:
      - ./data/dolphinscheduler-api/dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - ./data/dolphinscheduler-api/dolphinscheduler-shared-local:/opt/soft
      - ./data/dolphinscheduler-api/dolphinscheduler-resource-local:/dolphinscheduler
      - ./jars/mysql-connector-java-8.0.16.jar:/opt/dolphinscheduler/libs/mysql-connector-java-8.0.16.jar
    networks:
      - dolphinscheduler

  dolphinscheduler-alert:
    image: apache/dolphinscheduler-alert-server:3.1.9
    profiles: ["all"]
    env_file: .env
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:50053/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ./data/dolphinscheduler-alert/dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - ./jars/mysql-connector-java-8.0.16.jar:/opt/dolphinscheduler/libs/mysql-connector-java-8.0.16.jar
    networks:
      - dolphinscheduler

  dolphinscheduler-master:
    image: apache/dolphinscheduler-master:3.1.9
    profiles: ["all"]
    env_file: .env
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:5679/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      dolphinscheduler-zookeeper:
        condition: service_healthy
    volumes:
      - ./data/dolphinscheduler-master/dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - ./data/dolphinscheduler-master/dolphinscheduler-shared-local:/opt/soft
      - ./jars/mysql-connector-java-8.0.16.jar:/opt/dolphinscheduler/libs/mysql-connector-java-8.0.16.jar
    networks:
      - dolphinscheduler

  dolphinscheduler-worker:
    image: apache/dolphinscheduler-worker:3.1.9
    profiles: ["all"]
    env_file: .env
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:1235/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      dolphinscheduler-zookeeper:
        condition: service_healthy
    volumes:
      - ./data/dolphinscheduler-worker/dolphinscheduler-worker-data:/tmp/dolphinscheduler
      - ./data/dolphinscheduler-worker/dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - ./data/dolphinscheduler-worker/dolphinscheduler-shared-local:/opt/soft
      - ./data/dolphinscheduler-worker/dolphinscheduler-resource-local:/dolphinscheduler
      - ./jars/mysql-connector-java-8.0.16.jar:/opt/dolphinscheduler/libs/mysql-connector-java-8.0.16.jar
    networks:
      - dolphinscheduler

  spark:
    image: tabulario/spark-iceberg
    platform: linux/arm64
    container_name: data-warehouse-spark
    profiles: ["all"]
    hostname: demo-spark-iceberg
    build: spark/
    volumes:
      - ./jars/paimon-spark-3.5-0.8.0.jar:/opt/spark/jars/paimon-spark-3.5-0.8.0.jar
      - ./jars/paimon-s3-0.8.0.jar:/opt/spark/jars/paimon-s3-0.8.0.jar
      - ./data/table:/opt/data
      - ./data/spark-conf:/opt/spark/conf
      - ./sql/prepare_data.sql:/opt/sql/prepare_data.sql
    depends_on:
      - rest
      - minio
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    networks:
      - dolphinscheduler

  rest:
    image: tabulario/iceberg-rest
    platform: linux/arm64
    container_name: data-warehouse-iceberg-rest
    profiles: ["all"]
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/wh/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
    networks:
      - dolphinscheduler
    volumes:
      - ./jars/jdk1.8.0_421:/opt/jdk1.8.0_421
      - ./data/doris-bin:/opt/doris-bin
      - ./scripts:/opt/scripts

  minio:
    image: minio/minio
    platform: linux/arm64
    container_name: data-warehouse-minio
    profiles: ["all"]
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      dolphinscheduler:
        aliases:
          - warehouse.minio
    command: [ "server", "/data", "--console-address", ":9001" ]

  mc:
    depends_on:
      - minio
    image: minio/mc:RELEASE.2024-10-02T08-27-28Z-cpuv1
    platform: linux/arm64
    container_name: data-warehouse-mc
    profiles: ["all"]
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    networks:
      - dolphinscheduler
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "

  jobmanager:
    image: flink:1.18.0
    platform: linux/arm64
    container_name: data-warehouse-jobmanager
    profiles: ["all"]
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    ports:
      - "8082:8081"
    command: jobmanager
    depends_on:
      - rest
      - minio
    volumes:
      - ./jars/flink-connector-jdbc-3.1.2-1.18.jar:/opt/flink/lib/flink-connector-jdbc-3.1.2-1.18.jar
      - ./jars/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
      - ./jars/flink-s3-fs-hadoop-1.18.0.jar:/opt/flink/plugins/s3-fs-hadoop/flink-s3-fs-hadoop-1.18.0.jar
      - ./jars/flink-sql-connector-kafka-3.1.0-1.18.jar:/opt/flink/lib/flink-sql-connector-kafka-3.1.0-1.18.jar
      - ./jars/iceberg-flink-runtime-1.18-1.5.2.jar:/opt/flink/lib/iceberg-flink-runtime-1.18-1.5.2.jar
      - ./jars/iceberg-aws-bundle-1.5.2.jar:/opt/flink/lib/iceberg-aws-bundle-1.5.2.jar
      - ./jars/paimon-flink-1.18-0.8.0.jar:/opt/flink/lib/paimon-flink-1.18-0.8.0.jar
      - ./jars/paimon-s3-0.8.0.jar:/opt/flink/lib/paimon-s3-0.8.0.jar
      - ./sql/init_tables.sql:/opt/flink/sql/init_tables.sql
      - ./data/flink-conf:/opt/flink/conf
    networks:
      - dolphinscheduler
    deploy:
      replicas: 1

  taskmanager:
    image: flink:1.18.0
    platform: linux/arm64
    profiles: ["all"]
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./jars/flink-connector-jdbc-3.1.2-1.18.jar:/opt/flink/lib/flink-connector-jdbc-3.1.2-1.18.jar
      - ./jars/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
      - ./jars/flink-s3-fs-hadoop-1.18.0.jar:/opt/flink/plugins/s3-fs-hadoop/flink-s3-fs-hadoop-1.18.0.jar
      - ./jars/flink-sql-connector-kafka-3.1.0-1.18.jar:/opt/flink/lib/flink-sql-connector-kafka-3.1.0-1.18.jar
      - ./jars/iceberg-flink-runtime-1.18-1.5.2.jar:/opt/flink/lib/iceberg-flink-runtime-1.18-1.5.2.jar
      - ./jars/iceberg-aws-bundle-1.5.2.jar:/opt/flink/lib/iceberg-aws-bundle-1.5.2.jar
      - ./jars/paimon-flink-1.18-0.8.0.jar:/opt/flink/lib/paimon-flink-1.18-0.8.0.jar
      - ./jars/paimon-s3-0.8.0.jar:/opt/flink/lib/paimon-s3-0.8.0.jar
    networks:
      - dolphinscheduler
    deploy:
      replicas: 2

  dinky:
    image: dinkydocker/dinky-standalone-server:1.2-flink1.18
    container_name: dinky
    profiles: ["all"]
    ports:
      - "8888:8888"
    environment:
      #      DB_ACTIVE: mysql
      MYSQL_ADDR: mysql:3306
      MYSQL_DATABASE: dinky
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
    networks:
      - dolphinscheduler

  superset:
    image: selectdb/superset_3.0.1-cloud_3.0.3:latest
    container_name: data-warehouse-superset
    profiles: ["all"]
#    user: "root"
    environment:
      SUPERSET_SECRET_KEY: "doris"
    command:
      - "sh"
      - "-c"
      - |
        superset db upgrade
        superset fab create-admin --username admin --password doris --firstname Superset --lastname Admin --email admin@superset.com
        superset init
        /bin/sh -c /usr/bin/run-server.sh
    ports:
      - "8088:8088"
    networks:
      - dolphinscheduler

  python-producer:
    image: python:3.9
    container_name: python-producer
    working_dir: /app
    volumes:
      - ./scripts/datageneration:/app
    command: bash -c "pip install -r requirements.txt && python main_batch_run.py"
    networks:
      - dolphinscheduler

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    ports:
      - "8080:8080"
    volumes:
      - ./data/nocodb:/usr/app/data
    networks:
      - dolphinscheduler


networks:
  dolphinscheduler:
    driver: bridge

volumes:
  mysql:
  dolphinscheduler-zookeeper:
  dolphinscheduler-worker-data:
  dolphinscheduler-logs:
  dolphinscheduler-shared-local:
  dolphinscheduler-resource-local:
