CREATE OR REPLACE VIEW yshopping_dwd.dwd_canonical_inventory_migration_assessment_event AS
SELECT
    event_id,
    tenant_id,
    aggregate_id AS assessment_id,
    aggregate_version AS assessment_version,
    occurred_at,
    recorded_at,
    correlation_id,
    causation_id,
    idempotency_key,
    get_json_string(payload, '$.migration_run_id') AS migration_run_id,
    get_json_string(payload, '$.assessment_id') AS payload_assessment_id,
    get_json_string(payload, '$.legacy_balance_id') AS legacy_balance_id,
    get_json_string(payload, '$.source_system') AS migration_source_system,
    get_json_string(payload, '$.source_type') AS migration_source_type,
    get_json_string(payload, '$.source_id') AS source_id,
    get_json_string(payload, '$.source_classification') AS source_classification,
    CAST(get_json_string(payload, '$.source_version') AS BIGINT) AS source_version,
    CAST(REPLACE(SUBSTR(get_json_string(payload, '$.source_updated_at'), 1, 19), 'T', ' ') AS DATETIME) AS source_updated_at,
    get_json_string(payload, '$.source_snapshot_hash') AS source_snapshot_hash,
    get_json_string(payload, '$.source_owner_id') AS source_owner_id,
    get_json_string(payload, '$.resolved_owner_type') AS resolved_owner_type,
    get_json_string(payload, '$.resolved_owner_id') AS resolved_owner_id,
    get_json_string(payload, '$.source_sku_id') AS source_sku_id,
    get_json_string(payload, '$.resolved_canonical_sku_id') AS resolved_canonical_sku_id,
    get_json_string(payload, '$.source_warehouse_id') AS source_warehouse_id,
    get_json_string(payload, '$.resolved_warehouse_id') AS resolved_warehouse_id,
    get_json_string(payload, '$.source_location_id') AS source_location_id,
    get_json_string(payload, '$.resolved_location_id') AS resolved_location_id,
    get_json_string(payload, '$.source_lot_id') AS source_lot_id,
    get_json_string(payload, '$.resolved_lot_id') AS resolved_lot_id,
    get_json_string(payload, '$.lot_tracking_policy') AS lot_tracking_policy,
    get_json_string(payload, '$.stock_status') AS stock_status,
    get_json_string(payload, '$.quality_status') AS quality_status,
    get_json_string(payload, '$.source_uom_code') AS source_uom_code,
    get_json_string(payload, '$.resolved_base_uom_code') AS resolved_base_uom_code,
    CAST(get_json_string(payload, '$.source_on_hand_quantity') AS DECIMAL(24,6)) AS source_on_hand_quantity,
    CAST(get_json_string(payload, '$.source_reserved_quantity') AS DECIMAL(24,6)) AS source_reserved_quantity,
    CAST(get_json_string(payload, '$.source_in_transit_quantity') AS DECIMAL(24,6)) AS source_in_transit_quantity,
    CAST(get_json_string(payload, '$.active_reservation_count') AS BIGINT) AS active_reservation_count,
    CAST(get_json_string(payload, '$.active_reservation_quantity') AS DECIMAL(24,6)) AS active_reservation_quantity,
    CAST(get_json_string(payload, '$.reservation_allocation_count') AS BIGINT) AS reservation_allocation_count,
    CAST(get_json_string(payload, '$.reservation_allocation_quantity') AS DECIMAL(24,6)) AS reservation_allocation_quantity,
    get_json_string(payload, '$.assessment_status') AS assessment_status,
    get_json_string(payload, '$.blocker_codes') AS blocker_codes_json,
    get_json_string(payload, '$.policy_version') AS policy_version,
    get_json_string(payload, '$.verification_ref') AS verification_ref,
    CAST(REPLACE(SUBSTR(get_json_string(payload, '$.assessed_at'), 1, 19), 'T', ' ') AS DATETIME) AS assessed_at
FROM yshopping_dwd.dwd_domain_event
WHERE event_type = 'inventory.migration.balance_assessed'
  AND schema_version IN (1, 2)
  AND source_system = 'cloudmold-inventory'
  AND aggregate_type = 'inventory_migration_assessment';
