CREATE OR REPLACE VIEW yshopping_dwd.dwd_canonical_inventory_migration_pilot_item_event AS
SELECT
    event_id,
    tenant_id,
    aggregate_id AS pilot_item_id,
    aggregate_version AS item_version,
    occurred_at,
    recorded_at,
    correlation_id,
    causation_id,
    idempotency_key,
    get_json_string(payload, '$.pilot_batch_id') AS pilot_batch_id,
    get_json_string(payload, '$.pilot_item_id') AS payload_pilot_item_id,
    CAST(get_json_string(payload, '$.manifest_ordinal') AS BIGINT) AS manifest_ordinal,
    get_json_string(payload, '$.item_scope_hash') AS item_scope_hash,
    get_json_string(payload, '$.manifest_hash') AS manifest_hash,
    get_json_string(payload, '$.migration_run_id') AS migration_run_id,
    get_json_string(payload, '$.assessment_id') AS assessment_id,
    get_json_string(payload, '$.source_system') AS migration_source_system,
    get_json_string(payload, '$.source_type') AS migration_source_type,
    get_json_string(payload, '$.source_id') AS source_id,
    get_json_string(payload, '$.source_classification') AS source_classification,
    CAST(get_json_string(payload, '$.source_version') AS BIGINT) AS source_version,
    CAST(REPLACE(SUBSTR(get_json_string(payload, '$.source_updated_at'),1,19),'T',' ') AS DATETIME) AS source_updated_at,
    get_json_string(payload, '$.source_snapshot_hash') AS source_snapshot_hash,
    CAST(get_json_string(payload, '$.source_on_hand_quantity') AS DECIMAL(24,6)) AS source_on_hand_quantity,
    CAST(get_json_string(payload, '$.source_reserved_quantity') AS DECIMAL(24,6)) AS source_reserved_quantity,
    CAST(get_json_string(payload, '$.source_in_transit_quantity') AS DECIMAL(24,6)) AS source_in_transit_quantity,
    CAST(get_json_string(payload, '$.active_reservation_count') AS BIGINT) AS active_reservation_count,
    CAST(get_json_string(payload, '$.active_reservation_quantity') AS DECIMAL(24,6)) AS active_reservation_quantity,
    get_json_string(payload, '$.owner_type') AS owner_type,
    get_json_string(payload, '$.owner_id') AS owner_id,
    get_json_string(payload, '$.owner_mapping_id') AS owner_mapping_id,
    CAST(get_json_string(payload, '$.owner_mapping_version') AS BIGINT) AS owner_mapping_version,
    get_json_string(payload, '$.owner_mapping_evidence_ref') AS owner_mapping_evidence_ref,
    get_json_string(payload, '$.canonical_sku_id') AS canonical_sku_id,
    get_json_string(payload, '$.sku_mapping_id') AS sku_mapping_id,
    CAST(get_json_string(payload, '$.sku_mapping_version') AS BIGINT) AS sku_mapping_version,
    get_json_string(payload, '$.sku_mapping_evidence_ref') AS sku_mapping_evidence_ref,
    get_json_string(payload, '$.warehouse_source_mapping_id') AS warehouse_source_mapping_id,
    CAST(get_json_string(payload, '$.warehouse_mapping_version') AS BIGINT) AS warehouse_mapping_version,
    get_json_string(payload, '$.warehouse_mapping_evidence_ref') AS warehouse_mapping_evidence_ref,
    get_json_string(payload, '$.warehouse_id') AS warehouse_id,
    get_json_string(payload, '$.location_source_mapping_id') AS location_source_mapping_id,
    CAST(get_json_string(payload, '$.location_mapping_version') AS BIGINT) AS location_mapping_version,
    get_json_string(payload, '$.location_mapping_evidence_ref') AS location_mapping_evidence_ref,
    get_json_string(payload, '$.location_id') AS location_id,
    get_json_string(payload, '$.zone_id') AS zone_id,
    get_json_string(payload, '$.lot_tracking_policy') AS lot_tracking_policy,
    get_json_string(payload, '$.lot_id') AS lot_id,
    get_json_string(payload, '$.lot_mapping_id') AS lot_mapping_id,
    CAST(get_json_string(payload, '$.lot_mapping_version') AS BIGINT) AS lot_mapping_version,
    get_json_string(payload, '$.lot_evidence_ref') AS lot_evidence_ref,
    get_json_string(payload, '$.stock_status') AS stock_status,
    get_json_string(payload, '$.quality_status') AS quality_status,
    get_json_string(payload, '$.base_uom_code') AS base_uom_code,
    CAST(get_json_string(payload, '$.uom_conversion_ratio') AS DECIMAL(24,9)) AS uom_conversion_ratio,
    get_json_string(payload, '$.uom_evidence_ref') AS uom_evidence_ref,
    get_json_string(payload, '$.authoritative_record_ref') AS authoritative_record_ref,
    get_json_string(payload, '$.quantity_evidence_ref') AS quantity_evidence_ref,
    get_json_string(payload, '$.source_cdc_position') AS source_cdc_position,
    CAST(REPLACE(SUBSTR(get_json_string(payload, '$.source_extracted_at'),1,19),'T',' ') AS DATETIME) AS source_extracted_at,
    CAST(get_json_string(payload, '$.target_balance_absent') AS BOOLEAN) AS target_balance_absent,
    CAST(get_json_string(payload, '$.bridge_absent') AS BOOLEAN) AS bridge_absent,
    get_json_string(payload, '$.item_status') AS item_status,
    CAST(get_json_string(payload, '$.execution_available') AS BOOLEAN) AS execution_available
FROM yshopping_dwd.dwd_domain_event
WHERE event_type='inventory.migration.pilot_item_status_changed'
  AND schema_version=1
  AND source_system='cloudmold-inventory'
  AND aggregate_type='inventory_migration_pilot_item';
