CREATE OR REPLACE VIEW yshopping_dwd.dwd_canonical_after_sale_resolution_saga_event AS
SELECT
    event_id, schema_version, tenant_id, aggregate_id AS saga_id, aggregate_version,
    occurred_at, recorded_at, correlation_id, causation_id, idempotency_key,
    get_json_string(payload, '$.run_id') AS run_id,
    get_json_string(payload, '$.saga_id') AS payload_saga_id,
    get_json_string(payload, '$.after_sale_id') AS after_sale_id,
    get_json_string(payload, '$.after_sale_item_id') AS after_sale_item_id,
    get_json_string(payload, '$.order_id') AS order_id,
    get_json_string(payload, '$.order_item_id') AS order_item_id,
    get_json_string(payload, '$.payment_id') AS payment_id,
    get_json_string(payload, '$.return_fulfillment_id') AS return_fulfillment_id,
    get_json_string(payload, '$.return_shipment_id') AS return_shipment_id,
    get_json_string(payload, '$.inspection_id') AS inspection_id,
    get_json_string(payload, '$.canonical_sku_id') AS canonical_sku_id,
    CAST(get_json_string(payload, '$.quantity') AS DECIMAL(24,6)) AS quantity,
    get_json_string(payload, '$.previous_status') AS previous_status,
    get_json_string(payload, '$.current_status') AS current_status,
    get_json_string(payload, '$.active_step') AS active_step,
    CAST(get_json_string(payload, '$.step_ordinal') AS INT) AS step_ordinal,
    CAST(get_json_string(payload, '$.attempt') AS INT) AS attempt,
    json_query(payload, '$.checkpoints') AS checkpoints,
    CAST(get_json_string(payload, '$.accepted_quantity') AS DECIMAL(24,6)) AS accepted_quantity,
    CAST(get_json_string(payload, '$.returned_quantity') AS DECIMAL(24,6)) AS returned_quantity,
    get_json_string(payload, '$.uom_code') AS uom_code,
    CAST(get_json_string(payload, '$.approved_amount_minor') AS BIGINT) AS approved_amount_minor,
    COALESCE(CAST(get_json_string(payload, '$.gross_amount_minor') AS BIGINT),
             CAST(get_json_string(payload, '$.approved_amount_minor') AS BIGINT)) AS gross_amount_minor,
    COALESCE(CAST(get_json_string(payload, '$.benefit_amount_minor') AS BIGINT), 0) AS benefit_amount_minor,
    COALESCE(CAST(get_json_string(payload, '$.net_amount_minor') AS BIGINT),
             CAST(get_json_string(payload, '$.approved_amount_minor') AS BIGINT)) AS net_amount_minor,
    CAST(get_json_string(payload, '$.refunded_amount_minor') AS BIGINT) AS refunded_amount_minor,
    get_json_string(payload, '$.currency_code') AS currency_code,
    CAST(get_json_string(payload, '$.inventory_operation_id') AS BIGINT) AS inventory_operation_id,
    CAST(get_json_string(payload, '$.inventory_ledger_transaction_id') AS BIGINT) AS inventory_ledger_transaction_id,
    COALESCE(get_json_string(payload, '$.benefit_reversal_status'), 'NOT_REQUIRED') AS benefit_reversal_status,
    get_json_string(payload, '$.benefit_reversal_batch_id') AS benefit_reversal_batch_id,
    COALESCE(CAST(get_json_string(payload, '$.benefit_reversal_amount_minor') AS BIGINT), 0)
        AS benefit_reversal_amount_minor,
    CAST(get_json_string(payload, '$.payment_refund_transaction_id') AS BIGINT) AS payment_refund_transaction_id,
    get_json_string(payload, '$.order_settlement_effect_id') AS order_settlement_effect_id,
    CAST(get_json_string(payload, '$.order_settlement_version') AS BIGINT) AS order_settlement_version,
    get_json_bool(payload, '$.order_return_full') AS order_return_full,
    CAST(get_json_string(payload, '$.order_refund_operation_id') AS BIGINT) AS order_refund_operation_id,
    CAST(get_json_string(payload, '$.order_return_operation_id') AS BIGINT) AS order_return_operation_id,
    CAST(get_json_string(payload, '$.order_version') AS BIGINT) AS order_version,
    get_json_string(payload, '$.error_code') AS error_code,
    get_json_string(payload, '$.error_message') AS error_message,
    get_json_string(payload, '$.next_retry_at') AS next_retry_at
FROM yshopping_dwd.dwd_domain_event
WHERE event_type = 'after_sale.resolution_saga.status.changed'
  AND schema_version IN (1, 2, 3)
  AND source_system = 'cloudmold-aftersales';
