CREATE OR REPLACE VIEW yshopping_dwd.dwd_canonical_catalog_sku_snapshot AS
SELECT
    event_id,
    tenant_id,
    aggregate_id AS canonical_sku_id,
    aggregate_version,
    get_json_string(payload, '$.canonical_style_id') AS canonical_style_id,
    get_json_string(payload, '$.style_code') AS style_code,
    get_json_string(payload, '$.style_name') AS style_name,
    get_json_string(payload, '$.brand_ref') AS brand_ref,
    get_json_string(payload, '$.planning_category_ref') AS planning_category_ref,
    CAST(get_json_string(payload, '$.planning_year') AS INT) AS planning_year,
    get_json_string(payload, '$.season_code') AS season_code,
    get_json_string(payload, '$.wave_code') AS wave_code,
    get_json_string(payload, '$.canonical_spu_id') AS canonical_spu_id,
    get_json_string(payload, '$.spu_code') AS spu_code,
    get_json_string(payload, '$.product_name') AS product_name,
    get_json_string(payload, '$.sales_category_ref') AS sales_category_ref,
    get_json_string(payload, '$.sku_code') AS sku_code,
    get_json_string(payload, '$.variant_key') AS variant_key,
    get_json_string(payload, '$.variant_key_hash') AS variant_key_hash,
    get_json_string(payload, '$.color_id') AS color_id,
    get_json_string(payload, '$.color_code') AS color_code,
    get_json_string(payload, '$.color_name') AS color_name,
    get_json_string(payload, '$.size_group_id') AS size_group_id,
    get_json_string(payload, '$.size_group_code') AS size_group_code,
    get_json_string(payload, '$.size_id') AS size_id,
    get_json_string(payload, '$.size_code') AS size_code,
    get_json_string(payload, '$.size_name') AS size_name,
    get_json_string(payload, '$.base_uom_code') AS base_uom_code,
    get_json_string(payload, '$.primary_barcode') AS primary_barcode,
    get_json_string(payload, '$.status') AS catalog_status,
    correlation_id,
    occurred_at,
    recorded_at
FROM yshopping_dwd.dwd_domain_event
WHERE event_type = 'catalog.sku.defined' AND schema_version = 1;
