CREATE OR REPLACE VIEW yshopping_dwd.dwd_canonical_order_benefit_funding_event AS
SELECT
    allocation.event_id,
    allocation.schema_version,
    allocation.tenant_id,
    allocation.envelope_order_id,
    allocation.aggregate_version,
    allocation.event_sequence,
    allocation.run_id,
    allocation.order_id,
    allocation.order_no,
    allocation.benefit_application_id,
    allocation.application_key,
    allocation.benefit_allocation_id,
    allocation.allocation_key,
    allocation.order_item_id,
    allocation.line_key,
    allocation.amount_minor AS allocation_amount_minor,
    allocation.currency_code AS allocation_currency_code,
    allocation.occurred_at,
    allocation.recorded_at,
    get_json_string(funding.`value`, '$.benefit_funding_id') AS benefit_funding_id,
    get_json_string(funding.`value`, '$.funding_key') AS funding_key,
    get_json_string(funding.`value`, '$.funder_type') AS funder_type,
    get_json_string(funding.`value`, '$.funder_id') AS funder_id,
    CAST(get_json_string(funding.`value`, '$.amount_minor') AS BIGINT) AS amount_minor,
    get_json_string(funding.`value`, '$.currency_code') AS currency_code
FROM yshopping_dwd.dwd_canonical_order_benefit_allocation_event allocation,
     LATERAL json_each(allocation.funding) funding;
