#!/usr/bin/env python3
"""Materialize rich local/demo supply-chain candidates through governed Temporal workflows."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import subprocess
import urllib.error
import urllib.parse
import urllib.request
import uuid


TENANT_ID = int(os.environ.get("CLOUDMOLD_AUTOMATION_TENANT_ID", "162"))
OPERATOR_ID = int(os.environ.get("CLOUDMOLD_AUTOMATION_OPERATOR_ID", "225"))
BASE_URL = os.environ.get("CLOUDMOLD_ADMIN_API_URL", "http://127.0.0.1:48080/admin-api")
MYSQL_DATABASE = os.environ.get("CLOUDMOLD_MYSQL_DATABASE", "ruoyi-vue-pro")
PRINCIPAL = "9a0df287-0b0d-4e07-a114-8487bad79b73"
SUPPLIER_SUBMITTER = "1d9634aa-f54c-4c81-96dc-d3b61d5486d7"
SUPPLIER_REVIEWER = "38fb8735-2be3-429e-877f-17d19715fedb"
TARGET_WAREHOUSE_ID = "62d10000-0000-4000-8000-000000000001"
TARGET_LOCATION_ID = "62d10000-0000-4000-8000-000000000202"

SKILLS = {
    "stock-count": ("skill.cloudmold.inventory.stock-count-lifecycle.v1", "managed-daily-inventory-stock-count-lifecycle"),
    "scrap": ("skill.cloudmold.inventory.scrap-lifecycle.v1", "managed-daily-inventory-scrap-lifecycle"),
    "inventory-control": ("skill.cloudmold.inventory.control-evidence-lifecycle.v1", "managed-daily-inventory-control-evidence-lifecycle"),
    "supplier-admission": ("skill.cloudmold.supplier.admission-lifecycle.v1", "managed-daily-supplier-admission-lifecycle"),
    "warehouse-transfer": ("skill.cloudmold.warehouse.stock-transfer-lifecycle.v1", "managed-daily-warehouse-stock-transfer-lifecycle"),
}
SUPPLIER_NAMES = ("潮屿精选供应链", "元境潮品贸易", "澄海鞋服供应", "北辰机能制造", "曜石生活选品")
TOKEN: str | None = None


def mysql(sql: str) -> list[list[str]]:
    host = os.environ.get("CLOUDMOLD_MYSQL_HOST")
    if host:
        command = ["mysql", "-N", "-B", "-h", host, "-u", os.environ.get("CLOUDMOLD_MYSQL_USER", "root"), MYSQL_DATABASE, "-e", sql]
    ssl_ca = os.environ.get("CLOUDMOLD_MYSQL_SSL_CA")
    if ssl_ca:
        # The local MySQL image uses a CA-pinned autogenerated server
        # certificate without a DNS subjectAltName. VERIFY_CA keeps TLS and
        # CA verification without asking it to satisfy that absent hostname
        # extension inside the Compose network.
        ssl_mode = os.environ.get("CLOUDMOLD_MYSQL_SSL_MODE")
        ssl_arguments = ["--ssl-ca=" + ssl_ca]
        if ssl_mode:
            ssl_arguments.append("--ssl-mode=" + ssl_mode)
        else:
            ssl_arguments.append("--skip-ssl-verify-server-cert")
        command[1:1] = ssl_arguments
        environment = os.environ.copy()
        password = environment.get("CLOUDMOLD_MYSQL_PASSWORD")
        if password:
            environment["MYSQL_PWD"] = password
    else:
        command = ["docker", "exec", "yudao-mysql", "mysql", "-uroot", "-p123456", "-N", "-B", "-e", sql]
        environment = None
    completed = subprocess.run(command, text=True, capture_output=True, check=False, env=environment)
    if completed.returncode:
        raise RuntimeError(completed.stderr.strip() or "automation database query failed")
    return [line.split("\t") for line in completed.stdout.splitlines() if line.strip()]


def access_token() -> str:
    rows = mysql(
        f"SELECT refresh_token FROM `{MYSQL_DATABASE}`.system_oauth2_access_token "
        f"WHERE tenant_id={TENANT_ID} AND user_id={OPERATOR_ID} AND expires_time>UTC_TIMESTAMP(6) "
        "ORDER BY expires_time DESC LIMIT 1"
    )
    if not rows:
        raise RuntimeError("no active automation operator refresh token")
    url = BASE_URL + "/system/auth/refresh-token?refreshToken=" + urllib.parse.quote(rows[0][0], safe="")
    request = urllib.request.Request(url, data=b"", method="POST", headers={"tenant-id": str(TENANT_ID)})
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = json.load(response)
    token = payload.get("data", {}).get("accessToken") if payload.get("code") == 0 else None
    if not token:
        raise RuntimeError("automation operator token refresh failed")
    return token


def api(method: str, path: str, body: dict | None = None) -> dict:
    global TOKEN
    if TOKEN is None:
        TOKEN = access_token()
    request = urllib.request.Request(
        BASE_URL + path,
        data=None if body is None else json.dumps(body, ensure_ascii=False, separators=(",", ":")).encode(),
        method=method,
        headers={"Authorization": "Bearer " + TOKEN, "tenant-id": str(TENANT_ID), "Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            payload = json.load(response)
    except urllib.error.HTTPError as error:
        raise RuntimeError(error.read().decode()) from error
    if payload.get("code") != 0:
        raise RuntimeError(json.dumps(payload, ensure_ascii=False))
    return payload.get("data") or {}


def now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat().replace("+00:00", "Z")


def new_id() -> str:
    return str(uuid.uuid4())


def sha(value: str) -> str:
    return hashlib.sha256(value.encode()).hexdigest()


def command(operation: str, suffix: str, **fields: object) -> dict:
    return {"operation": operation, "idempotencyKey": "candidate-" + suffix,
            "sourceEventId": "supply-operations-" + suffix, "correlationId": new_id(),
            "occurredAt": now(), "actorPrincipalId": PRINCIPAL, **fields}


def balance(where: str, offset: int = 0) -> list[str]:
    rows = mysql(
        "SELECT balance_id,owner_type,owner_id,canonical_sku_id,warehouse_id,location_id,"
        "COALESCE(lot_id,''),stock_status,quality_status,base_uom_code,on_hand_quantity "
        f"FROM `{MYSQL_DATABASE}`.cloudmold_inventory_balance_v3 WHERE tenant_id={TENANT_ID} AND {where} "
        f"ORDER BY updated_at DESC LIMIT 1 OFFSET {max(0, offset)}"
    )
    if not rows:
        raise RuntimeError("no eligible inventory balance")
    return rows[0]


def transferable_balance(offset: int = 0) -> list[str]:
    rows = mysql(
        "SELECT b.balance_id,b.owner_type,b.owner_id,b.canonical_sku_id,b.warehouse_id,b.location_id,"
        "b.lot_id,b.stock_status,b.quality_status,b.base_uom_code,b.on_hand_quantity "
        f"FROM `{MYSQL_DATABASE}`.cloudmold_inventory_balance_v3 b "
        f"JOIN `{MYSQL_DATABASE}`.cloudmold_inventory_lot l "
        "ON l.tenant_id=b.tenant_id AND l.lot_id=b.lot_id "
        f"WHERE b.tenant_id={TENANT_ID} AND l.status='ACTIVE' AND b.on_hand_quantity>=1 "
        "AND b.stock_status='SELLABLE' AND b.quality_status='QUALIFIED' "
        f"AND b.warehouse_id<>'{TARGET_WAREHOUSE_ID}' "
        f"ORDER BY b.updated_at DESC LIMIT 1 OFFSET {max(0, offset)}"
    )
    if not rows:
        raise RuntimeError("no active inventory lot is eligible for warehouse transfer")
    return rows[0]


def stock_count_payload(index: int) -> dict:
    b = balance("on_hand_quantity>=5 AND stock_status='SELLABLE' AND quality_status='QUALIFIED'", index % 6)
    count_id, line_id = new_id(), new_id()
    counted = str(max(0, int(float(b[10])) - 1))
    line = {"lineId": line_id, "lineNumber": 1, "ownerType": b[1], "ownerId": b[2], "canonicalSkuId": b[3],
            "warehouseId": b[4], "locationId": b[5], "lotId": b[6] or None, "stockStatus": b[7],
            "qualityStatus": b[8], "baseUomCode": b[9], "remark": "潮流仓实盘复核"}
    return {"commands": [
        command("CREATE_DRAFT", "count-create-" + count_id, stockCountId=count_id,
                stockCountCode="CMCOUNT" + uuid.uuid4().hex[:10].upper(), countMode="BLIND_COUNT",
                scopeType="EXPLICIT_LINES", scopeLabel="潮流仓盘点巡检", sourceBusinessType="SUPPLY_OPERATIONS",
                sourceBusinessRef=count_id, reasonCode="PERIODIC_COUNT", remark="日常库存治理", lines=[line]),
        command("SUBMIT", "count-submit-" + count_id, stockCountId=count_id),
        command("START_COUNTING", "count-start-" + count_id, stockCountId=count_id),
        command("RECORD_COUNT_BATCH", "count-record-" + count_id, stockCountId=count_id,
                countBatch={"batchId": new_id(), "batchNo": "CMBATCH" + uuid.uuid4().hex[:8].upper(),
                            "remark": "货位复核", "lines": [{"executionLineId": new_id(), "stockCountLineId": line_id,
                            "countedOnHandQuantity": counted, "remark": "账实差异复核"}]}),
        command("APPROVE_DIFFERENCE", "count-approve-" + count_id, stockCountId=count_id, approvalRemark="差异已完成责任复核"),
        command("ADJUST", "count-adjust-" + count_id, stockCountId=count_id),
        command("COMPLETE", "count-complete-" + count_id, stockCountId=count_id),
    ]}


def scrap_payload(index: int) -> dict:
    b = balance("on_hand_quantity>=5 AND stock_status='SELLABLE' AND quality_status='QUALIFIED'", index % 6)
    scrap_id, line_id = new_id(), new_id()
    return {"commands": [
        command("CREATE_DRAFT", "scrap-create-" + scrap_id, scrapId=scrap_id,
                scrapCode="CMSCRAP" + uuid.uuid4().hex[:10].upper(), reasonCode="DAMAGED", remark="潮品质损处置",
                ownerType=b[1], ownerId=b[2], warehouseId=b[4], lines=[{"lineId": line_id, "lineNumber": 1,
                "canonicalSkuId": b[3], "locationId": b[5], "lotId": b[6] or None, "stockStatus": b[7],
                "qualityStatus": b[8], "baseUomCode": b[9], "requestedQuantity": "1", "evidenceType": "QUALITY",
                "evidenceRef": "quality:" + sha(scrap_id), "remark": "品控判定不可售"}]),
        command("SUBMIT", "scrap-submit-" + scrap_id, scrapId=scrap_id, reasonCode="DAMAGED", ownerType=b[1], ownerId=b[2], warehouseId=b[4]),
        command("APPROVE", "scrap-approve-" + scrap_id, scrapId=scrap_id, reasonCode="DAMAGED", ownerType=b[1], ownerId=b[2], warehouseId=b[4]),
        command("RECORD_DISPOSITION_BATCH", "scrap-disposition-" + scrap_id, scrapId=scrap_id, reasonCode="DAMAGED", ownerType=b[1], ownerId=b[2], warehouseId=b[4],
                dispositionBatch={"batchId": new_id(), "batchNo": "CMDISP" + uuid.uuid4().hex[:8].upper(), "dispositionType": "DESTROYED", "proofType": "PHOTO", "proofRef": "proof:" + sha(scrap_id + "proof"), "remark": "质损货品完成处置", "lines": [{"dispositionLineId": new_id(), "lineNumber": 1, "disposedQuantity": "1", "remark": "完成处置"}]}),
        command("COMPLETE", "scrap-complete-" + scrap_id, scrapId=scrap_id, reasonCode="DAMAGED", ownerType=b[1], ownerId=b[2], warehouseId=b[4]),
    ]}


def control_payload(index: int) -> dict:
    rows = mysql(
        "SELECT b.balance_id,b.owner_type,b.owner_id,b.canonical_sku_id,b.warehouse_id,b.location_id,COALESCE(b.lot_id,''),b.stock_status,b.quality_status,b.base_uom_code,b.on_hand_quantity "
        f"FROM `{MYSQL_DATABASE}`.cloudmold_inventory_balance_v3 b WHERE b.tenant_id={TENANT_ID} AND b.on_hand_quantity>=1 "
        f"AND NOT EXISTS (SELECT 1 FROM `{MYSQL_DATABASE}`.cloudmold_safety_stock_policy p WHERE p.tenant_id=b.tenant_id AND p.owner_type=b.owner_type AND p.owner_id=b.owner_id AND p.canonical_sku_id=b.canonical_sku_id AND p.warehouse_network_id=b.warehouse_id AND p.status='PUBLISHED' AND p.effective_to IS NULL) ORDER BY b.updated_at DESC LIMIT 1 OFFSET {index % 3}"
    )
    if not rows:
        raise RuntimeError("all available inventory scopes already have a published safety-stock policy")
    b = rows[0]
    policy_id, snapshot_id = new_id(), new_id()
    base_policy = {"policyId": policy_id, "policyCode": "CMSAFE" + uuid.uuid4().hex[:10].upper(), "ownerType": b[1], "ownerId": b[2], "canonicalSkuId": b[3], "warehouseNetworkId": b[4], "effectiveFrom": dt.date.today().isoformat(), "targetServiceLevelBasisPoints": 9500, "safetyStockQuantity": "8", "reorderPointQuantity": "20", "maximumStockQuantity": "80", "replenishmentCycleDays": 7, "leadTimeDays": 14, "policyBasisCode": "SERVICE_LEVEL_V1", "policySha256": sha(policy_id), "evidenceRef": "inventory-control:" + policy_id}
    return {"policy": {"actorPrincipalId": PRINCIPAL, "commands": [
        {"operation": "SAVE_DRAFT", "idempotencyKey": "candidate", "runId": "candidate", "correlationId": new_id(), "occurredAt": now(), "policy": base_policy},
        {"operation": "APPROVE", "idempotencyKey": "candidate", "runId": "candidate", "correlationId": new_id(), "occurredAt": now(), "policy": {"policyId": policy_id, "expectedVersion": 1}},
        {"operation": "PUBLISH", "idempotencyKey": "candidate", "runId": "candidate", "correlationId": new_id(), "occurredAt": now(), "policy": {"policyId": policy_id, "expectedVersion": 2}},
    ]}, "health": {"actorPrincipalId": PRINCIPAL, "command": {"idempotencyKey": "candidate", "runId": "candidate", "correlationId": new_id(), "occurredAt": now(), "snapshot": {"snapshotId": snapshot_id, "snapshotCode": "CMHEALTH" + uuid.uuid4().hex[:8].upper(), "policyId": policy_id, "policyVersionId": "workflow-bound", "ledgerWatermarkRef": "inventory-ledger:" + b[0], "ledgerWatermarkOccurredAt": now(), "stockoutCount": 0, "lowStockCount": 1, "overstockCount": 0, "obsoleteCount": 0, "agedCount": 1, "shelfLifeRiskCount": 0, "shortageQuantity": "3", "excessQuantity": "0", "atRiskQuantity": "1", "snapshotSha256": sha(snapshot_id), "issueRefs": []}}}, "aging": {"idempotencyKey": "candidate", "sourceEventId": new_id(), "correlationId": new_id(), "occurredAt": now(), "ownerType": b[1], "ownerId": b[2], "warehouseId": b[4], "bucketPolicyCode": "STANDARD_AGING", "bucketPolicyVersion": "1.0.0", "ageFreshMaxDays": 30, "ageAgingMaxDays": 90, "ageStaleMaxDays": 180, "expiryWarningMaxDays": 60, "expiryCriticalMaxDays": 30}}


def supplier_admission_payload(index: int) -> dict:
    supplier_id, suffix = new_id(), uuid.uuid4().hex[:8].upper()
    name = SUPPLIER_NAMES[index % len(SUPPLIER_NAMES)]
    return {"commands": [
        {"actorPrincipalId": PRINCIPAL, "command": {"operation": "REGISTER_SUPPLIER", "idempotencyKey": "candidate", "runId": "candidate", "correlationId": new_id(), "occurredAt": now(), "supplier": {"supplierId": supplier_id, "supplierCode": "CMSUP" + suffix, "supplierName": name, "countryCode": "CN", "capabilitySummary": "潮流鞋服、生活方式货品、质检与多仓履约能力", "riskLevel": "LOW", "reasonCode": "SUPPLY_OPERATIONS"}}},
        {"actorPrincipalId": SUPPLIER_SUBMITTER, "command": {"operation": "SUBMIT_ADMISSION", "idempotencyKey": "candidate", "runId": "candidate", "correlationId": new_id(), "occurredAt": now(), "admission": {"supplierId": supplier_id, "qualificationEvidenceSha256": sha(supplier_id + ":qualification"), "riskEvidenceSha256": sha(supplier_id + ":risk"), "reasonCode": "SUPPLY_OPERATIONS", "expectedVersion": 1}}},
        {"actorPrincipalId": SUPPLIER_REVIEWER, "command": {"operation": "APPROVE_ADMISSION", "idempotencyKey": "candidate", "runId": "candidate", "correlationId": new_id(), "occurredAt": now(), "admission": {"supplierId": supplier_id, "reasonCode": "SUPPLY_OPERATIONS", "expectedVersion": 2}}},
    ]}


def warehouse_transfer_payload(index: int) -> dict:
    b = transferable_balance(index % 1)
    suffix, execution_line_id = uuid.uuid4().hex[:10].upper(), new_id()
    source_ref = "supply-rebalance-" + suffix.lower()
    return {"commands": [
        {"operation": "CREATE_APPROVED_REQUEST", "idempotencyKey": "candidate", "sourceEventId": "sup-trf-" + suffix.lower(), "correlationId": new_id(), "occurredAt": now(), "requestCode": "CMTRRQ" + suffix, "orderCode": "CMTROD" + suffix, "sourceBusinessType": "SUPPLY_REBALANCE", "sourceBusinessRef": source_ref, "ownerType": b[1], "ownerId": b[2], "sourceWarehouseId": b[4], "targetWarehouseId": TARGET_WAREHOUSE_ID, "reasonCode": "REBALANCE_APPROVED", "remark": "潮流货盘跨仓补位", "lines": [{"lineNumber": 10, "canonicalSkuId": b[3], "requestedQuantity": "1", "uomCode": b[9], "remark": "核心货盘补位"}]},
        {"operation": "COMPLETE_OUTBOUND_BATCH", "idempotencyKey": "candidate", "sourceEventId": "sup-out-" + suffix.lower(), "correlationId": new_id(), "occurredAt": now(), "orderId": "", "outboundBatch": {"batchNo": "CMOUT" + suffix, "remark": "源仓完成出库", "lines": [{"executionLineId": execution_line_id, "lineNumber": 10, "quantity": "1", "lotId": b[6], "sourceLocationId": b[5], "sourceStockStatus": b[7], "sourceQualityStatus": b[8], "targetLocationId": TARGET_LOCATION_ID, "targetStockStatus": b[7], "targetQualityStatus": b[8], "remark": "调拨出库"}]}},
        {"operation": "COMPLETE_RECEIPT_BATCH", "idempotencyKey": "candidate", "sourceEventId": "sup-rcv-" + suffix.lower(), "correlationId": new_id(), "occurredAt": now(), "orderId": "", "receiptBatch": {"batchNo": "CMRCV" + suffix, "remark": "目标仓完成收货", "lines": [{"executionLineId": new_id(), "outboundExecutionLineId": execution_line_id, "quantity": "1", "remark": "调拨收货"}]}}
    ]}


def enqueue(kind: str, payload: dict, sequence: int) -> dict:
    skill_id, schedule_suffix = SKILLS[kind]
    nonce = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d%H%M%S") + "-" + uuid.uuid4().hex[:10]
    candidate = api("POST", "/cloudmold/ai-operations/temporal-automation/candidates", {
        "clientRequestKey": f"supply-operations-{kind}-{nonce}", "skillId": skill_id, "skillVersion": "1.0.0",
        "businessKey": f"supply-operations/{kind}/{nonce}", "inputJson": json.dumps(payload, ensure_ascii=False, separators=(",", ":")),
    })
    schedule_id = f"cloudmold-t{TENANT_ID}-{schedule_suffix}"
    api("POST", "/cloudmold/ai-operations/temporal-schedules/" + urllib.parse.quote(schedule_id, safe="") + "/trigger")
    return {"kind": kind, "candidateId": candidate.get("candidateId"), "status": candidate.get("status"), "scheduleId": schedule_id, "sequence": sequence}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rounds", type=int, default=1)
    parser.add_argument("--round-size", type=int, default=4)
    args = parser.parse_args()
    builders = {"stock-count": stock_count_payload, "scrap": scrap_payload, "inventory-control": control_payload, "supplier-admission": supplier_admission_payload, "warehouse-transfer": warehouse_transfer_payload}
    rotation = ["stock-count", "scrap", "warehouse-transfer", "supplier-admission", "inventory-control"]
    results: list[dict] = []
    sequence = 0
    for round_index in range(max(1, args.rounds)):
        for item_index in range(max(1, args.round_size)):
            kind = rotation[(round_index * max(1, args.round_size) + item_index) % len(rotation)]
            sequence += 1
            try:
                results.append(enqueue(kind, builders[kind](sequence), sequence))
            except Exception as error:
                results.append({"kind": kind, "status": "SKIPPED", "sequence": sequence, "reason": str(error)})
    print(json.dumps({"tenantId": TENANT_ID, "results": results}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
