#!/usr/bin/env python3
"""Approve eligible pending supply-chain workflow decisions through the governed MCP path."""

from __future__ import annotations

import datetime as dt
import os
import subprocess
import sys
import uuid
from pathlib import Path


TENANT_ID = int(os.environ.get("CLOUDMOLD_AUTOMATION_TENANT_ID", "162"))
APPROVER_IDS = tuple(
    int(value) for value in os.environ.get(
        "CLOUDMOLD_AUTOMATION_APPROVER_IDS", "227,228,229").split(",")
    if value.strip()
)
SCRIPT_ROOT = Path(os.environ.get("CLOUDMOLD_SKILL_ROOT", "/app/skills"))
MCP_URL = os.environ.get("CLOUDMOLD_MCP_URL", "http://127.0.0.1:49090")
TOKEN_FILE = Path(os.environ.get(
    "CLOUDMOLD_MCP_TOKEN_FILE", "/run/secrets/cloudmold_mcp_bearer_token"))

SUPPLY_CHAIN_ACTIONS = (
    "procurement.sourcing-award", "purchase-order.dispatch", "procurement.receipt-accounting",
    "replenishment.end-to-end", "warehouse.physical-cycle", "warehouse.admission",
    "supply-planning.sop-release", "replenishment.convert", "supplier.return",
    "finance.supplier-return-finalization", "finance.supplier-invoice-finalization",
    "inventory.stock-count", "inventory.scrap", "inventory.policy-health-capture",
    "inventory.stock-transfer", "warehouse.stock-transfer", "supplier.admission",
)


def mysql(sql: str) -> list[str]:
    command = [
        "mysql", "-N", "-B", "-h", os.environ.get("CLOUDMOLD_MYSQL_HOST", "yudao-mysql"),
        "-u", os.environ.get("CLOUDMOLD_MYSQL_USER", "root"),
        os.environ.get("CLOUDMOLD_MYSQL_DATABASE", "ruoyi-vue-pro"), "-e", sql,
    ]
    ssl_ca = os.environ.get("CLOUDMOLD_MYSQL_SSL_CA")
    if ssl_ca:
        # The local MySQL image's CA-pinned autogenerated server certificate
        # has no DNS subjectAltName. VERIFY_CA preserves TLS and CA trust
        # without requiring that absent hostname extension.
        ssl_mode = os.environ.get("CLOUDMOLD_MYSQL_SSL_MODE")
        ssl_arguments = ["--ssl-ca=" + ssl_ca]
        if ssl_mode:
            ssl_arguments.append("--ssl-mode=" + ssl_mode)
        else:
            ssl_arguments.append("--skip-ssl-verify-server-cert")
        command[1:1] = ssl_arguments
    environment = os.environ.copy()
    password = environment.get("CLOUDMOLD_MYSQL_PASSWORD")
    if password:
        environment["MYSQL_PWD"] = password
    completed = subprocess.run(command, text=True, capture_output=True, check=False, env=environment)
    if completed.returncode:
        raise RuntimeError(completed.stderr.strip() or "automation database query failed")
    return [line.strip() for line in completed.stdout.splitlines() if line.strip()]


def pending_approval_ids(operator_id: int, limit: int) -> list[str]:
    actions = ",".join("'" + action + "'" for action in SUPPLY_CHAIN_ACTIONS)
    rows = mysql(
        "SELECT DISTINCT a.approval_id FROM cloudmold_agent_approval a "
        "JOIN cloudmold_agent_approval_workflow_binding b "
        "ON b.tenant_id=a.tenant_id AND b.approval_id=a.approval_id "
        "JOIN ACT_RU_TASK t ON t.PROC_INST_ID_=b.process_instance_id "
        f"WHERE a.tenant_id={TENANT_ID} AND a.status='PENDING' AND a.action_code IN ({actions}) "
        f"AND t.ASSIGNEE_='{operator_id}' "
        "AND t.TASK_DEF_KEY_ IN ('ai_approval_review','responsibility_confirmation') "
        "ORDER BY a.approval_id ASC "
        f"LIMIT {limit}"
    )
    return list(dict.fromkeys(rows))


def main() -> int:
    limit = max(1, int(os.environ.get("CLOUDMOLD_AUTOMATION_APPROVAL_LIMIT", "60")))
    if not APPROVER_IDS:
        raise RuntimeError("at least one AI approver identity is required")
    reviewer = SCRIPT_ROOT / "cloudmold-hsf-mcp-operator" / "scripts" / "ai_approval_batch.py"
    submitted = 0
    for operator_id in APPROVER_IDS:
        approval_ids = pending_approval_ids(operator_id, limit)
        if not approval_ids:
            continue
        run_id = "supply-chain-ai-review-" + str(operator_id) + "-" \
            + dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d%H%M%S") + "-" + uuid.uuid4().hex[:8]
        command = [
            sys.executable, str(reviewer), "--run-id", run_id, "--tenant-id", str(TENANT_ID),
            "--operator-id", str(operator_id), "--mcp-url", MCP_URL,
            "--token-file", str(TOKEN_FILE), *approval_ids,
        ]
        completed = subprocess.run(command, text=True)
        if completed.returncode == 0:
            submitted += len(approval_ids)
    if submitted == 0:
        print('{"status":"NO_PENDING_SUPPLY_CHAIN_APPROVAL"}')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
