version: "3.9"
services:

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./data/zookeeper:/bitnami/zookeeper  # 持久化 Zookeeper 数据
    networks:
      - app_network

  kafka-cp-kafka-headless:
    image: bitnami/kafka:latest
    container_name: kafka-cp-kafka-headless
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.7:2181/kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.7:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    volumes:
      - ./data/kafka:/bitnami/kafka        # 持久化 Kafka 数据
      - /etc/localtime:/etc/localtime
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"
    networks:
      - app_network

  ### Schema Registry ###

  schema-registry:
    image: confluentinc/cp-schema-registry:5.0.0
    hostname: schema-registry
    ports:
      - "18081:18081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-cp-kafka-headless:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:18081
    depends_on:
      - kafka-cp-kafka-headless
    networks:
      - app_network

  ### Schema Registry UI ###

  schema-registry-ui:
    image: landoop/schema-registry-ui:0.9.4
    hostname: schema-registry-ui
    ports:
      - "8001:8000"
    environment:
      SCHEMAREGISTRY_URL: http://schema-registry:18081/
    depends_on:
      - schema-registry
    networks:
      - app_network

#  hbase:
#    image: harisekhon/hbase:latest # 或指定版本，例如 harisekhon/hbase:1.4
#    container_name: hbase
#    hostname: docker-hbase
#    ports:
#      - "2181:2181"   # Zookeeper
#      - "8080:8080"   # HBase REST
#      - "8085:8085"   # REST backup
#      - "9090:9090"   # Thrift API
#      - "9000:9000"   # HBase Master WebUI
#      - "9095:9095"   # Thrift backup
#      - "16000:16000" # HBase Master
#      - "16010:16010" # HBase Master Web UI
#      - "16201:16201" # HBase RegionServer Web UI
#      - "16301:16301" # HBase RegionServer backup
#      - "16020:16020" # HBase RegionServer

  hbase:
    container_name: hbase
    image: xinze0803/hbase
    links:
      - zookeeper
    depends_on:
      - zookeeper
    ports:
      - "16010:16010"
      - "8080:8080"
      - "9090:9090"
      - "16000:16000"
      - "16020:16020"
      - "16030:16030"
    command: [ "/wait-for-it.sh", "zookeeper:2181", "-t", "10", "--", "/usr/bin/supervisord" ]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
