version: "3.8"

services:

  riskcontrol-redis:
    image: redis:6.2
    container_name: riskcontrol-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - riskcontrol_network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"

  riskcontrol-postgresql:
    image: bitnami/postgresql:15.2.0
    container_name: riskcontrol-postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: riskcontrol
    volumes:
      - postgresql_data:/bitnami/postgresql
      - ./init/postgresql:/docker-entrypoint-initdb.d
    networks:
      - riskcontrol_network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"

  learn-zookeeper:
    image: bitnami/zookeeper:latest
    container_name: learn-zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - riskcontrol_network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"

  learn-kafka:
    image: bitnami/kafka:latest
    container_name: learn-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: learn-zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_EXTERNAL://0.0.0.0:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://learn-kafka:9092,PLAINTEXT_EXTERNAL://localhost:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_NUM_PARTITIONS: 3
      KAFKA_LOG_DIRS: /bitnami/kafka/logs
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - riskcontrol_network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"

  learn-kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: learn-kafka-ui
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "learn-kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "learn-zookeeper:2181"
    networks:
      - riskcontrol_network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"

volumes:
  redis_data:
  postgresql_data:
  zookeeper_data:
  kafka_data:

networks:
  riskcontrol_network:
    driver: bridge
