version: "3.8"

networks:
  kafka-net:
    driver: bridge

services:
  kafka1:
    image: bitnami/kafka:3.5.1
    container_name: kafka1
    restart: always
    networks:
      - kafka-net
    volumes:
      - ./data/kafka_raft/kafka1:/bitnami/kafka
    environment:
      TZ: "Asia/Shanghai"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      BITNAMI_DEBUG: "true"
      ALLOW_PLAINTEXT_LISTENER: "no"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_NUM_PARTITIONS: "1"
      KAFKA_CFG_LISTENERS: "INTERNAL://:9094,CLIENT://:9095,CONTROLLER://:9093,EXTERNAL://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka1:9094,CLIENT://kafka1:9095,EXTERNAL://192.168.1.7:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_CLIENT_USERS: "vpn"
      KAFKA_CLIENT_PASSWORDS: "BCfoV77N"
      KAFKA_INTER_BROKER_USER: "vpn"
      KAFKA_INTER_BROKER_PASSWORD: "BCfoV77N"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_KRAFT_CLUSTER_ID: "abcdefghijklmnopqrstuv"
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx4G"
    ports:
      - "9092:9092"

  kafka2:
    image: bitnami/kafka:3.5.1
    container_name: kafka2
    restart: always
    networks:
      - kafka-net
    volumes:
      - ./data/kafka_raft/kafka2:/bitnami/kafka
    environment:
      TZ: "Asia/Shanghai"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      BITNAMI_DEBUG: "true"
      ALLOW_PLAINTEXT_LISTENER: "no"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_NUM_PARTITIONS: "1"
      KAFKA_CFG_LISTENERS: "INTERNAL://:9094,CLIENT://:9095,CONTROLLER://:9093,EXTERNAL://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka2:9094,CLIENT://kafka2:9095,EXTERNAL://192.168.1.7:9096"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_CLIENT_USERS: "vpn"
      KAFKA_CLIENT_PASSWORDS: "BCfoV77N"
      KAFKA_INTER_BROKER_USER: "vpn"
      KAFKA_INTER_BROKER_PASSWORD: "BCfoV77N"
      KAFKA_CFG_NODE_ID: "2"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_KRAFT_CLUSTER_ID: "abcdefghijklmnopqrstuv"
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx4G"
    ports:
      - "9096:9092"

  kafka3:
    image: bitnami/kafka:3.5.1
    container_name: kafka3
    restart: always
    networks:
      - kafka-net
    volumes:
      - ./data/kafka_raft/kafka3:/bitnami/kafka
    environment:
      TZ: "Asia/Shanghai"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      BITNAMI_DEBUG: "true"
      ALLOW_PLAINTEXT_LISTENER: "no"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_NUM_PARTITIONS: "1"
      KAFKA_CFG_LISTENERS: "INTERNAL://:9094,CLIENT://:9095,CONTROLLER://:9093,EXTERNAL://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka3:9094,CLIENT://kafka3:9095,EXTERNAL://192.168.1.7:9097"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_CLIENT_USERS: "vpn"
      KAFKA_CLIENT_PASSWORDS: "BCfoV77N"
      KAFKA_INTER_BROKER_USER: "vpn"
      KAFKA_INTER_BROKER_PASSWORD: "BCfoV77N"
      KAFKA_CFG_NODE_ID: "3"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_KRAFT_CLUSTER_ID: "abcdefghijklmnopqrstuv"
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx4G"
    ports:
      - "9097:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:master
    container_name: kafka-ui
    restart: always
    networks:
      - kafka-net
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      DYNAMIC_CONFIG_ENABLED: "true"
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: "admin"
      SPRING_SECURITY_USER_PASSWORD: "admin"
